apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rcs5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-rcs5
    app.kubernetes.io/part-of: load-app-843fab1f-7c0d-46f1-9f0c-27e28d36b385
  name: devfile-sample-code-with-mz74
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-code-with-quarkus-rcs5
    weight: null
status: {}
